#Requires -Version 7
# ================================================================
# Cleanup script for keiba_ai disk space (~8.7 GB recoverable)
# Run from the repository root: pwsh -File .\cleanup_disk_space.ps1
# ================================================================

$base = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $base

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host "  keiba_ai  Disk Cleanup  (~8.7 GB)" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""

# --- Target list ---
$targets = @(
    @{ Path = "archive\model_v2.pkl";             Note = "deprecated model (7.2 GB)" }
    @{ Path = "archive\model_v8.pkl";             Note = "duplicate of root model_v8.pkl (458 MB)" }
    @{ Path = "archive\keiba_data_features.csv";  Note = "old copy (536 MB)" }
    @{ Path = "archive\keiba_data.csv";           Note = "old copy (146 MB)" }
    @{ Path = "model_v2.pkl";                     Note = "deprecated (7.2 GB)" }
    @{ Path = "model_v3.pkl";                     Note = "deprecated (42 MB)" }
    @{ Path = "model_v4.pkl";                     Note = "deprecated (41 MB)" }
    @{ Path = "model_v5.pkl";                     Note = "deprecated (43 MB)" }
    @{ Path = "model_v6.pkl";                     Note = "deprecated (40 MB)" }
    @{ Path = "model_v7.pkl";                     Note = "deprecated (85 MB)" }
)

Write-Host "Files to DELETE:" -ForegroundColor Yellow
$found = @()
foreach ($t in $targets) {
    $full = Join-Path $base $t.Path
    if (Test-Path $full) {
        $sz = [math]::Round((Get-Item $full).Length / 1MB, 0)
        Write-Host ("  [{0,6} MB]  {1}  ({2})" -f $sz, $t.Path, $t.Note) -ForegroundColor Red
        $found += $full
    }
}

Write-Host ""
Write-Host "Directories to CLEAN (auto-regenerated by Python):" -ForegroundColor Yellow
Write-Host "  All __pycache__  and  .pytest_cache" -ForegroundColor DarkYellow
Write-Host ""
Write-Host "KEEP (not touched):" -ForegroundColor Green
Write-Host "  model_v8.pkl          (active model, 111 MB)" -ForegroundColor Green
Write-Host "  archive\secret_envs\  (credentials)" -ForegroundColor Green
Write-Host "  data\, logs\, reports\" -ForegroundColor Green
Write-Host ""

if ($found.Count -eq 0) {
    Write-Host "No target files found. Nothing to delete." -ForegroundColor Green
    exit 0
}

$ans = Read-Host "Proceed with deletion? [y/N]"
if ($ans -ne 'y' -and $ans -ne 'Y') {
    Write-Host "Cancelled." -ForegroundColor Gray
    exit 0
}

Write-Host ""
Write-Host "--- Deleting files ---" -ForegroundColor Cyan

$freed = 0L
foreach ($f in $found) {
    $sz = (Get-Item $f).Length
    Remove-Item $f -Force
    $freed += $sz
    Write-Host ("  DELETED  {0}  ({1:N0} MB)" -f (Split-Path $f -Leaf), [math]::Round($sz/1MB,0)) -ForegroundColor Green
}

Write-Host ""
Write-Host "--- Cleaning __pycache__ ---" -ForegroundColor Cyan
$cacheCount = 0
Get-ChildItem $base -Recurse -Directory -Filter "__pycache__" | ForEach-Object {
    Remove-Item $_.FullName -Recurse -Force -ErrorAction SilentlyContinue
    $cacheCount++
}
Write-Host "  Removed $cacheCount __pycache__ directories" -ForegroundColor Green

Write-Host ""
Write-Host "--- Cleaning .pytest_cache ---" -ForegroundColor Cyan
Get-ChildItem $base -Recurse -Directory -Filter ".pytest_cache" | ForEach-Object {
    Remove-Item $_.FullName -Recurse -Force -ErrorAction SilentlyContinue
}
Write-Host "  Done" -ForegroundColor Green

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ("  Freed: {0:N1} GB" -f ($freed / 1GB)) -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""

Write-Host "Remaining model files:" -ForegroundColor White
Get-ChildItem $base -Filter "model_v*.pkl" -ErrorAction SilentlyContinue |
    Select-Object Name, @{N="MB";E={[math]::Round($_.Length/1MB,1)}} |
    Format-Table -AutoSize
